### ISSUE TITLE
Add GAP Appearance Values

### ISSUE THREAD

**Issue by eriklins** [NordicSemiconductor/bluetooth-numbers-database#106]
Any plans for adding another JSON with the GAP Appearance Values (BT SiG [Assigned Numbers document](https://www.bluetooth.com/wp-content/uploads/Files/Specification/Assigned_Numbers.pdf) section 2.6)...?

Would you accept a pull-request if I would add a JSON file with these?

**Comment by dinesharjani** [comment]
@eriklins we don't have "plans" at the moment, since I'm juggling many things. And we have big incoming hardware this year (Apple Vision Pro), Mac release of nRF Connect, etc.

If you want to do a pull request, I'd by all means accept it. Just keep in mind this would need to be a /v2, to not break existing users of /v1 if you change the format too much, and that the scripts would also need to be updated.

**Comment by eriklins** [comment]
Thanks for following up. I would not change any of the existing JSON files but would rather add an additional one containing the GAP appearance values. This should hence not conflict with anyone using just the existing JSON files, so a /v2 but not be necessary. Thoughts?

**Comment by dinesharjani** [comment]
I'd love to see it. My only concern is that the data type is clear, in the sense that, for example, there are multiple types of "temperature" data, or ways of storing a float, etc. That was my initial reason for not getting into this mess. But sure, I'd love to see your PR. If it includes patches for the scripts where necessary (or if necessary) and the types look extensible for other Data as well as not confusing to see / understand from the perspective of someone using this library, I think this could be a win for everyone.

**Comment by eriklins** [comment]
Solved with [#10](https://github.com/NordicSemiconductor/bluetooth-numbers-database/pull/107) and issue can be closed. Thanks all.
